const routes = {
  ADMIN_DASHBOARD: "/admin",
  AGENT_DASHBOARD: "/agent",
  SUPER_ADMIN_DASHBOARD: "/superadmin",
  LOGIN: "/login",
  UNAUTHORIZED: "/unauthorized",
  CUSTOMERS: "/customers",
  CUSTOMER_ADD: "/customers/add",
  CUSTOMER_DETAIL: "/customers/:id",
  CUSTOMER_EDIT: "/customers/:id/edit",
  PLANS: "/plans",
  PLAN_DETAIL: "/plans/:id",
  PLAN_EDIT: "/plans/:id/edit",
  AGENTS: "/agents",
  AGENT_DETAIL: "/agents/:id",
  AGENT_EDIT: "/agents/:id/edit",
  COLLECTION: "/collection",
  PAYMENTS: "/payments",
  REPORTS: "/reports",
  INVOICE_HISTORY: "/reports/invoices",
  PAYMENT_HISTORY: "/reports/payments",
  USER_HISTORY: "/reports/user",
};

export default routes;
