export const BASE_URL = "https://broadbandx-be.vercel.app/api";
export const URLS = {
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  COMPANIES: "/companies",
  ADMINS_COMPANY: "/admins/company",
  ADMINS: "/admins",
  AGENTS: "/agents",
  CUSTOMERS: "/customers",
  AREAS: "/areas",
  SERVICES: "/services",
  PLANS: "/plans",
  ORDERS: "/orders",
  BILLING: "/billing",
  REPORTS: "/reports",
  SETTINGS: "/settings",
  NOTIFICATIONS: "/notifications",
  DASHBOARD_STATS: "/dashboard/stats",
  PAYMENTS: "/payments",
  DASHBOARD: "/dashboard",
};
